#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FriendsList

#include "Basic.hpp"

#include "InputCore_structs.hpp"
#include "MordhauOnlineSubsystem_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Mordhau_structs.hpp"
#include "PlayFab_structs.hpp"
#include "Engine_structs.hpp"
#include "E_FriendsListEntryType_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function BP_FriendsList.BP_FriendsList_C.ExecuteUbergraph_BP_FriendsList
// 0x10C0 (0x10C0 - 0x0000)
struct BP_FriendsList_C_ExecuteUbergraph_BP_FriendsList final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetEnteredText_Text;                      // 0x0018(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0040(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0050(0x0010)(ZeroConstructor, NoDestructor)
	TArray<class FString>                         K2Node_MakeArray_Array;                            // 0x0060(0x0010)(ConstParm, ReferenceParm)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0070(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(const TArray<struct FMordhauFriend>& Friends)> K2Node_CreateDelegate_OutputDelegate_3; // 0x0080(0x0010)(ZeroConstructor, NoDestructor)
	TArray<struct FMordhauFriend>                 K2Node_CustomEvent_Friends_1;                      // 0x0090(0x0010)(ConstParm, ReferenceParm)
	TArray<struct FMordhauFriend>                 K2Node_CustomEvent_Friends;                        // 0x00A0(0x0010)(ConstParm, ReferenceParm)
	TDelegate<void(const TArray<struct FMordhauFriend>& Friends)> K2Node_CreateDelegate_OutputDelegate_4; // 0x00B0(0x0010)(ZeroConstructor, NoDestructor)
	TArray<struct FMordhauFriend>                 Temp_struct_Variable;                              // 0x00C0(0x0010)(ReferenceParm)
	class UGetFriendsList*                        CallFunc_GetFriendsList_ReturnValue;               // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D9[0x7];                                       // 0x00D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FMordhauFriend>                 CallFunc_RemoveMordhauBlockedFriends_RealFriends;  // 0x00E0(0x0010)(ReferenceParm)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_5;            // 0x00F0(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_6;            // 0x0100(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_7;            // 0x0110(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_8;            // 0x0120(0x0010)(ZeroConstructor, NoDestructor)
	TArray<struct FPlayFabPlayer>                 K2Node_CustomEvent_Players_3;                      // 0x0130(0x0010)(ConstParm, ReferenceParm)
	TDelegate<void(const TArray<struct FPlayFabPlayer>& Players)> K2Node_CreateDelegate_OutputDelegate_9; // 0x0140(0x0010)(ZeroConstructor, NoDestructor)
	TArray<struct FPlayFabPlayer>                 K2Node_CustomEvent_Players_2;                      // 0x0150(0x0010)(ConstParm, ReferenceParm)
	TDelegate<void(const TArray<struct FPlayFabPlayer>& Players)> K2Node_CreateDelegate_OutputDelegate_10; // 0x0160(0x0010)(ZeroConstructor, NoDestructor)
	TArray<struct FPlayFabPlayer>                 Temp_struct_Variable_1;                            // 0x0170(0x0010)(ReferenceParm)
	class UGetBlockedPlayers*                     CallFunc_GetBlockedPlayers_ReturnValue;            // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_189[0x3];                                      // 0x0189(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_11;           // 0x018C(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_12;           // 0x019C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_1AC[0x4];                                      // 0x01AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x01B0(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue_1;        // 0x01B8(0x0008)(NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_13;           // 0x01C0(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(const TArray<struct FPlayFabPlayer>& Players)> K2Node_CreateDelegate_OutputDelegate_14; // 0x01D0(0x0010)(ZeroConstructor, NoDestructor)
	TArray<struct FPlayFabPlayer>                 K2Node_CustomEvent_Players_1;                      // 0x01E0(0x0010)(ConstParm, ReferenceParm)
	TArray<struct FPlayFabPlayer>                 K2Node_CustomEvent_Players;                        // 0x01F0(0x0010)(ConstParm, ReferenceParm)
	TDelegate<void(const TArray<struct FPlayFabPlayer>& Players)> K2Node_CreateDelegate_OutputDelegate_15; // 0x0200(0x0010)(ZeroConstructor, NoDestructor)
	TArray<struct FPlayFabPlayer>                 Temp_struct_Variable_2;                            // 0x0210(0x0010)(ReferenceParm)
	class UGetFriendRequests*                     CallFunc_GetFriendRequests_ReturnValue;            // 0x0220(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0228(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_229[0x3];                                      // 0x0229(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x022C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_16;           // 0x0230(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_17;           // 0x0240(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_IsFriend_IsFriend;                        // 0x0250(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_251[0x7];                                      // 0x0251(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0258(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0270(0x0040)(HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_1;          // 0x02B0(0x0018)()
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_1;                          // 0x02C8(0x0010)(ReferenceParm)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x02D8(0x0040)(HasGetValueTypeHash)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0318(0x0018)()
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_2;                          // 0x0330(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue_1;                     // 0x0340(0x0018)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_2;          // 0x0358(0x0018)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_3;          // 0x0370(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_2;            // 0x0388(0x0040)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_3;            // 0x03C8(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_3;                          // 0x0408(0x0010)(ReferenceParm)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_4;                          // 0x0418(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue_2;                     // 0x0428(0x0018)()
	class FText                                   CallFunc_Format_ReturnValue_3;                     // 0x0440(0x0018)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_4;          // 0x0458(0x0018)()
	bool                                          K2Node_CustomEvent_bUsedPlatform_1;                // 0x0470(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_471[0x3];                                      // 0x0471(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(bool bUsedPlatform)>           K2Node_CreateDelegate_OutputDelegate_18;           // 0x0474(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          K2Node_CustomEvent_bUsedPlatform;                  // 0x0484(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_485[0x3];                                      // 0x0485(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(bool bUsedPlatform)>           K2Node_CreateDelegate_OutputDelegate_19;           // 0x0488(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0498(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_499[0x3];                                      // 0x0499(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const struct FPlayFabPlayer& Player)> K2Node_CreateDelegate_OutputDelegate_20;    // 0x049C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_4AC[0x4];                                      // 0x04AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPlayFabPlayer                         K2Node_CustomEvent_Player_10;                      // 0x04B0(0x0060)(ConstParm, HasGetValueTypeHash)
	struct FPlayFabPlayer                         K2Node_CustomEvent_Player_9;                       // 0x0510(0x0060)(ConstParm, HasGetValueTypeHash)
	TDelegate<void(const struct FPlayFabPlayer& Player)> K2Node_CreateDelegate_OutputDelegate_21;    // 0x0570(0x0010)(ZeroConstructor, NoDestructor)
	struct FPlayFabPlayer                         Temp_struct_Variable_3;                            // 0x0580(0x0060)(HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x05E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EPlatform                                     Temp_byte_Variable;                                // 0x05E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5E2[0x6];                                      // 0x05E2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_5;                          // 0x05E8(0x0010)(ReferenceParm)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_6;                          // 0x05F8(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue_4;                     // 0x0608(0x0018)()
	class FText                                   CallFunc_Format_ReturnValue_5;                     // 0x0620(0x0018)()
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_22;           // 0x0638(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_23;           // 0x0648(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_24;           // 0x0658(0x0010)(ZeroConstructor, NoDestructor)
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0668(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x06A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6A4[0x4];                                      // 0x06A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x06A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_MordhauGameInstance_C*              K2Node_DynamicCast_AsBP_Mordhau_Game_Instance;     // 0x06B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x06B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsFriendsListAvailable_ReturnValue;       // 0x06B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6BA[0x6];                                      // 0x06BA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPlayFabPlayer                         K2Node_CustomEvent_Player_8;                       // 0x06C0(0x0060)(HasGetValueTypeHash)
	class AMordhauHUD*                            CallFunc_GetMordhauHUD_ReturnValue;                // 0x0720(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_FriendSearchDetailInfo_C*           CallFunc_Update_Invite_Friend_Detail_Info_Widget_BP_FriendDetailInfo; // 0x0728(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPlayFabPlayer                         K2Node_CustomEvent_Player_7;                       // 0x0730(0x0060)(HasGetValueTypeHash)
	class UBP_FriendSearchDetailInfo_C*           CallFunc_UpdateBlockFriendDetailInfoWidget_BP_FriendDetailInfo; // 0x0790(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AMordhauHUD*                            CallFunc_GetMordhauHUD_ReturnValue_1;              // 0x0798(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPlayFabPlayer                         K2Node_CustomEvent_Player_6;                       // 0x07A0(0x0060)(HasGetValueTypeHash)
	class UBlockPlayer*                           CallFunc_BlockPlayer_ReturnValue;                  // 0x0800(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_FriendSearchDetailInfo_C*           CallFunc_UpdateUnblockFriendDetailInfoWidget_BP_FriendDetailInfo; // 0x0808(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0810(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue;             // 0x0811(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_812[0x6];                                      // 0x0812(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AMordhauHUD*                            CallFunc_GetMordhauHUD_ReturnValue_2;              // 0x0818(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPlayFabPlayer                         K2Node_CustomEvent_Player_5;                       // 0x0820(0x0060)(HasGetValueTypeHash)
	class UUnblockPlayer*                         CallFunc_UnblockPlayer_ReturnValue;                // 0x0880(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x0888(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_889[0x7];                                      // 0x0889(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0890(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_ChoiceDialog_C*                     CallFunc_CreateChoiceDialog_ChoiceDialog;          // 0x0898(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AMordhauHUD*                            CallFunc_GetMordhauHUD_ReturnValue_3;              // 0x08A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class URemoveFriend*                          CallFunc_RemoveFriend_ReturnValue;                 // 0x08A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_5;          // 0x08B0(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_4;            // 0x08C8(0x0040)(HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x0908(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_909[0x7];                                      // 0x0909(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_7;                          // 0x0910(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue_6;                     // 0x0920(0x0018)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_6;          // 0x0938(0x0018)()
	bool                                          CallFunc_IsValid_ReturnValue_6;                    // 0x0950(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_951[0x7];                                      // 0x0951(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_TextInputDialog_C*                  CallFunc_Create_Text_Input_Dialog_TextInputDialog; // 0x0958(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_7;                    // 0x0960(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_961[0x7];                                      // 0x0961(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AMordhauHUD*                            CallFunc_GetMordhauHUD_ReturnValue_4;              // 0x0968(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_CustomEvent_Title;                          // 0x0970(0x0018)()
	class FText                                   K2Node_CustomEvent_Text;                           // 0x0988(0x0018)()
	class UBP_InformationDialog_C*                CallFunc_CreateInformationDialog_InformationDialog; // 0x09A0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_8;                    // 0x09A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9A9[0x7];                                      // 0x09A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AMordhauHUD*                            CallFunc_GetMordhauHUD_ReturnValue_5;              // 0x09B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPlayFabPlayer                         K2Node_CustomEvent_Player_4;                       // 0x09B8(0x0060)(HasGetValueTypeHash)
	class UDeclineFriendRequest*                  CallFunc_DeclineFriendRequest_ReturnValue;         // 0x0A18(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_9;                    // 0x0A20(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A21[0x7];                                      // 0x0A21(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPlayFabPlayer                         K2Node_CustomEvent_Player_3;                       // 0x0A28(0x0060)(HasGetValueTypeHash)
	struct FPlayFabPlayer                         K2Node_CustomEvent_Player_2;                       // 0x0A88(0x0060)(HasGetValueTypeHash)
	struct FPlayFabPlayer                         K2Node_CustomEvent_Player_1;                       // 0x0AE8(0x0060)(HasGetValueTypeHash)
	class UAcceptFriendRequest*                   CallFunc_AcceptFriendRequest_ReturnValue;          // 0x0B48(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPlayFabPlayer                         K2Node_CustomEvent_Player;                         // 0x0B50(0x0060)(HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_10;                   // 0x0BB0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_BB1[0x3];                                      // 0x0BB1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_25;           // 0x0BB4(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_BC4[0x4];                                      // 0x0BC4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FPlayFabPlayer>                 CallFunc_GetPartyInvites_ReturnValue;              // 0x0BC8(0x0010)(ReferenceParm)
	bool                                          CallFunc_DeclinePartyInvite_ReturnValue;           // 0x0BD8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_BD9[0x7];                                      // 0x0BD9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FPlayFabPlayer>                 CallFunc_Remove_Playfab_Blocked_Friend_RealFriends; // 0x0BE0(0x0010)(ReferenceParm)
	bool                                          CallFunc_AcceptPartyInvite_ReturnValue;            // 0x0BF0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_BF1[0x7];                                      // 0x0BF1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UBP_ReusableNavTabButton_C*>     K2Node_MakeArray_Array_8;                          // 0x0BF8(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0C08(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0C10(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x0C14(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_IntInt_ReturnValue;              // 0x0C18(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue_1;           // 0x0C19(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue_2;           // 0x0C1A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C1B[0x1];                                      // 0x0C1B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_26;           // 0x0C1C(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_27;           // 0x0C2C(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_28;           // 0x0C3C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_C4C[0x4];                                      // 0x0C4C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FUserSearchResult                      K2Node_CustomEvent_SearchResult_1;                 // 0x0C50(0x0078)()
	TDelegate<void(const struct FUserSearchResult& FriendSearchEntryData)> K2Node_CreateDelegate_OutputDelegate_29; // 0x0CC8(0x0010)(ZeroConstructor, NoDestructor)
	class UBP_FriendSearchDetailInfo_C*           CallFunc_UpdateAddFriendDetailInfoWidget_BP_FriendDetailInfo; // 0x0CD8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_7;          // 0x0CE0(0x0018)()
	bool                                          CallFunc_IsValid_ReturnValue_11;                   // 0x0CF8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CF9[0x7];                                      // 0x0CF9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_1;        // 0x0D00(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AMordhauHUD*                            CallFunc_GetMordhauHUD_ReturnValue_6;              // 0x0D08(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_CustomEvent_FriendsEntityId;                // 0x0D10(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_1;          // 0x0D28(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UFindPlayerByEntityId*                  CallFunc_FindPlayerByEntityId_ReturnValue;         // 0x0D38(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_30;           // 0x0D40(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_12;                   // 0x0D50(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D51[0x3];                                      // 0x0D51(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_31;           // 0x0D54(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_32;           // 0x0D64(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_D74[0x4];                                      // 0x0D74(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USendFriendRequest*                     CallFunc_SendFriendRequest_ReturnValue;            // 0x0D78(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPlayFabPlayer                         CallFunc_GetPlayFabPlayer_ReturnValue;             // 0x0D80(0x0060)(HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_StrStr_ReturnValue;              // 0x0DE0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_13;                   // 0x0DE1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_DE2[0x2];                                      // 0x0DE2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_33;           // 0x0DE4(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_34;           // 0x0DF4(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0E04(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E05[0x3];                                      // 0x0E05(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_35;           // 0x0E08(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_36;           // 0x0E18(0x0010)(ZeroConstructor, NoDestructor)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0E28(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E2C[0x4];                                      // 0x0E2C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_ChoiceDialog_C*                     CallFunc_CreateChoiceDialogWithContent_ChoiceContentDialog; // 0x0E30(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPlayFabPlayer                         CallFunc_Array_Get_Item;                           // 0x0E38(0x0060)(HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0E98(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsBlocked_IsBlocked;                      // 0x0E9C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_CustomEvent_bWasSuccessful_1;               // 0x0E9D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E9E[0x2];                                      // 0x0E9E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPlayFabApiError                       K2Node_CustomEvent_Error_1;                        // 0x0EA0(0x0038)(ConstParm)
	struct FUsernameSearchResult                  K2Node_CustomEvent_SearchResult;                   // 0x0ED8(0x0040)(ConstParm)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0F18(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0F1C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F1D[0x3];                                      // 0x0F1D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0F20(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F24[0x4];                                      // 0x0F24(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AMordhauHUD*                            CallFunc_GetMordhauHUD_ReturnValue_7;              // 0x0F28(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_MordhauHUD_C*                       K2Node_DynamicCast_AsBP_Mordhau_HUD;               // 0x0F30(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0F38(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F39[0x3];                                      // 0x0F39(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_37;           // 0x0F3C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_F4C[0x4];                                      // 0x0F4C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPlayFabAPI*                            CallFunc_GetPlayFabAPI_ReturnValue;                // 0x0F50(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPlayFabAPI*                            CallFunc_GetPlayFabAPI_ReturnValue_1;              // 0x0F58(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetShortID_ReturnValue;                   // 0x0F60(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetShortID_ReturnValue_1;                 // 0x0F70(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_8;          // 0x0F80(0x0018)()
	bool                                          K2Node_CustomEvent_bWasSuccessful;                 // 0x0F98(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F99[0x7];                                      // 0x0F99(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPlayFabApiError                       K2Node_CustomEvent_Error;                          // 0x0FA0(0x0038)(ConstParm)
	struct FGetPlayerByShortIdResult              K2Node_CustomEvent_ShortIdResults;                 // 0x0FD8(0x0038)(ConstParm)
	TDelegate<void(bool bWasSuccessful, const struct FPlayFabApiError& Error, const struct FGetPlayerByShortIdResult& ShortIdResults)> K2Node_CreateDelegate_OutputDelegate_38; // 0x1010(0x0010)(ZeroConstructor, NoDestructor)
	class FText                                   CallFunc_AddFriendByShortID_EntityID;              // 0x1020(0x0018)()
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x1038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x1039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsConsolePlatform_ReturnValue;            // 0x103A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EPlatform                                     CallFunc_GetPlatform_ReturnValue;                  // 0x103B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_103C[0x4];                                     // 0x103C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMordhauGameUserSettings*               CallFunc_GetMordhauGameUserSettings_ReturnValue;   // 0x1040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_2;        // 0x1048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetCrossplayEnabled_ReturnValue;          // 0x1050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_14;                   // 0x1051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EPlatform                                     K2Node_Select_Default;                             // 0x1052(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1053[0x5];                                     // 0x1053(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_ChoiceDialog_C*                     CallFunc_CreateChoiceDialogWithContent_ChoiceContentDialog_1; // 0x1058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_15;                   // 0x1060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1061[0x7];                                     // 0x1061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_3;        // 0x1068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_ChoiceDialog_C*                     CallFunc_CreateChoiceDialogWithContent_ChoiceContentDialog_2; // 0x1070(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_4;        // 0x1078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_16;                   // 0x1080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1081[0x7];                                     // 0x1081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_ChoiceDialog_C*                     CallFunc_CreateChoiceDialogWithContent_ChoiceContentDialog_3; // 0x1088(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_39;           // 0x1090(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_IsOfficial_ReturnValue;                   // 0x10A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsConsoleServer_ReturnValue;              // 0x10A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_10A2[0x6];                                     // 0x10A2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetServerID_ReturnValue;                  // 0x10A8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsEmpty_ReturnValue;                      // 0x10B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_FriendsList_C_ExecuteUbergraph_BP_FriendsList;

// Function BP_FriendsList.BP_FriendsList_C.OnShortIdResult
// 0x0078 (0x0078 - 0x0000)
struct BP_FriendsList_C_OnShortIdResult final
{
public:
	bool                                          bWasSuccessful;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPlayFabApiError                       Error;                                             // 0x0008(0x0038)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FGetPlayerByShortIdResult              ShortIdResults;                                    // 0x0040(0x0038)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_BP_FriendsList_C_OnShortIdResult;

// Function BP_FriendsList.BP_FriendsList_C.OnSearchUserNameCompleted
// 0x0080 (0x0080 - 0x0000)
struct BP_FriendsList_C_OnSearchUserNameCompleted final
{
public:
	bool                                          bWasSuccessful;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPlayFabApiError                       Error;                                             // 0x0008(0x0038)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FUsernameSearchResult                  SearchResult;                                      // 0x0040(0x0040)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_BP_FriendsList_C_OnSearchUserNameCompleted;

// Function BP_FriendsList.BP_FriendsList_C.OnFriendAddRequest
// 0x0018 (0x0018 - 0x0000)
struct BP_FriendsList_C_OnFriendAddRequest final
{
public:
	class FText                                   FriendsEntityId;                                   // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_BP_FriendsList_C_OnFriendAddRequest;

// Function BP_FriendsList.BP_FriendsList_C.ShowAddFriendDialog
// 0x0078 (0x0078 - 0x0000)
struct BP_FriendsList_C_ShowAddFriendDialog final
{
public:
	struct FUserSearchResult                      SearchResult;                                      // 0x0000(0x0078)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_BP_FriendsList_C_ShowAddFriendDialog;

// Function BP_FriendsList.BP_FriendsList_C.DeclinePartyInvite
// 0x0060 (0x0060 - 0x0000)
struct BP_FriendsList_C_DeclinePartyInvite final
{
public:
	struct FPlayFabPlayer                         Player_0;                                          // 0x0000(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_FriendsList_C_DeclinePartyInvite;

// Function BP_FriendsList.BP_FriendsList_C.AcceptPartyInvite
// 0x0060 (0x0060 - 0x0000)
struct BP_FriendsList_C_AcceptPartyInvite final
{
public:
	struct FPlayFabPlayer                         Player_0;                                          // 0x0000(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_FriendsList_C_AcceptPartyInvite;

// Function BP_FriendsList.BP_FriendsList_C.AcceptFriendRequest
// 0x0060 (0x0060 - 0x0000)
struct BP_FriendsList_C_AcceptFriendRequest final
{
public:
	struct FPlayFabPlayer                         Player_0;                                          // 0x0000(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_FriendsList_C_AcceptFriendRequest;

// Function BP_FriendsList.BP_FriendsList_C.ViewProfile
// 0x0060 (0x0060 - 0x0000)
struct BP_FriendsList_C_ViewProfile final
{
public:
	struct FPlayFabPlayer                         Player_0;                                          // 0x0000(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_FriendsList_C_ViewProfile;

// Function BP_FriendsList.BP_FriendsList_C.DeclineFriendRequest
// 0x0060 (0x0060 - 0x0000)
struct BP_FriendsList_C_DeclineFriendRequest final
{
public:
	struct FPlayFabPlayer                         Player_0;                                          // 0x0000(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_FriendsList_C_DeclineFriendRequest;

// Function BP_FriendsList.BP_FriendsList_C.ShowInfoDialog
// 0x0030 (0x0030 - 0x0000)
struct BP_FriendsList_C_ShowInfoDialog final
{
public:
	class FText                                   Title;                                             // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   Text;                                              // 0x0018(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_BP_FriendsList_C_ShowInfoDialog;

// Function BP_FriendsList.BP_FriendsList_C.ShowUnfriendDialog
// 0x0060 (0x0060 - 0x0000)
struct BP_FriendsList_C_ShowUnfriendDialog final
{
public:
	struct FPlayFabPlayer                         Player_0;                                          // 0x0000(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_FriendsList_C_ShowUnfriendDialog;

// Function BP_FriendsList.BP_FriendsList_C.ShowUnblockDialog
// 0x0060 (0x0060 - 0x0000)
struct BP_FriendsList_C_ShowUnblockDialog final
{
public:
	struct FPlayFabPlayer                         Player_0;                                          // 0x0000(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_FriendsList_C_ShowUnblockDialog;

// Function BP_FriendsList.BP_FriendsList_C.ShowBlockDialog
// 0x0060 (0x0060 - 0x0000)
struct BP_FriendsList_C_ShowBlockDialog final
{
public:
	struct FPlayFabPlayer                         Player_0;                                          // 0x0000(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_FriendsList_C_ShowBlockDialog;

// Function BP_FriendsList.BP_FriendsList_C.ShowInviteDialog
// 0x0060 (0x0060 - 0x0000)
struct BP_FriendsList_C_ShowInviteDialog final
{
public:
	struct FPlayFabPlayer                         Player_0;                                          // 0x0000(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_FriendsList_C_ShowInviteDialog;

// Function BP_FriendsList.BP_FriendsList_C.Tick
// 0x003C (0x003C - 0x0000)
struct BP_FriendsList_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_FriendsList_C_Tick;

// Function BP_FriendsList.BP_FriendsList_C.OnSuccess_217944CA49768150F6D0BB976B0A2882
// 0x0060 (0x0060 - 0x0000)
struct BP_FriendsList_C_OnSuccess_217944CA49768150F6D0BB976B0A2882 final
{
public:
	struct FPlayFabPlayer                         Player_0;                                          // 0x0000(0x0060)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_FriendsList_C_OnSuccess_217944CA49768150F6D0BB976B0A2882;

// Function BP_FriendsList.BP_FriendsList_C.OnFailure_217944CA49768150F6D0BB976B0A2882
// 0x0060 (0x0060 - 0x0000)
struct BP_FriendsList_C_OnFailure_217944CA49768150F6D0BB976B0A2882 final
{
public:
	struct FPlayFabPlayer                         Player_0;                                          // 0x0000(0x0060)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_FriendsList_C_OnFailure_217944CA49768150F6D0BB976B0A2882;

// Function BP_FriendsList.BP_FriendsList_C.OnSuccess_14FB086A4FA812D866B43EA884AB15A8
// 0x0001 (0x0001 - 0x0000)
struct BP_FriendsList_C_OnSuccess_14FB086A4FA812D866B43EA884AB15A8 final
{
public:
	bool                                          bUsedPlatform;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_FriendsList_C_OnSuccess_14FB086A4FA812D866B43EA884AB15A8;

// Function BP_FriendsList.BP_FriendsList_C.OnFailure_14FB086A4FA812D866B43EA884AB15A8
// 0x0001 (0x0001 - 0x0000)
struct BP_FriendsList_C_OnFailure_14FB086A4FA812D866B43EA884AB15A8 final
{
public:
	bool                                          bUsedPlatform;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_FriendsList_C_OnFailure_14FB086A4FA812D866B43EA884AB15A8;

// Function BP_FriendsList.BP_FriendsList_C.OnSuccess_569C408349C0C13C6D926BB27CA89F58
// 0x0010 (0x0010 - 0x0000)
struct BP_FriendsList_C_OnSuccess_569C408349C0C13C6D926BB27CA89F58 final
{
public:
	TArray<struct FPlayFabPlayer>                 Players;                                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_BP_FriendsList_C_OnSuccess_569C408349C0C13C6D926BB27CA89F58;

// Function BP_FriendsList.BP_FriendsList_C.OnFailure_569C408349C0C13C6D926BB27CA89F58
// 0x0010 (0x0010 - 0x0000)
struct BP_FriendsList_C_OnFailure_569C408349C0C13C6D926BB27CA89F58 final
{
public:
	TArray<struct FPlayFabPlayer>                 Players;                                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_BP_FriendsList_C_OnFailure_569C408349C0C13C6D926BB27CA89F58;

// Function BP_FriendsList.BP_FriendsList_C.OnSuccess_5E6108AB4A7566F6474069900CF80658
// 0x0010 (0x0010 - 0x0000)
struct BP_FriendsList_C_OnSuccess_5E6108AB4A7566F6474069900CF80658 final
{
public:
	TArray<struct FPlayFabPlayer>                 Players;                                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_BP_FriendsList_C_OnSuccess_5E6108AB4A7566F6474069900CF80658;

// Function BP_FriendsList.BP_FriendsList_C.OnFailure_5E6108AB4A7566F6474069900CF80658
// 0x0010 (0x0010 - 0x0000)
struct BP_FriendsList_C_OnFailure_5E6108AB4A7566F6474069900CF80658 final
{
public:
	TArray<struct FPlayFabPlayer>                 Players;                                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_BP_FriendsList_C_OnFailure_5E6108AB4A7566F6474069900CF80658;

// Function BP_FriendsList.BP_FriendsList_C.OnSuccess_5E28D2E54F38B10486BDCDAC1A2F5032
// 0x0010 (0x0010 - 0x0000)
struct BP_FriendsList_C_OnSuccess_5E28D2E54F38B10486BDCDAC1A2F5032 final
{
public:
	TArray<struct FMordhauFriend>                 Friends;                                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_BP_FriendsList_C_OnSuccess_5E28D2E54F38B10486BDCDAC1A2F5032;

// Function BP_FriendsList.BP_FriendsList_C.OnFailure_5E28D2E54F38B10486BDCDAC1A2F5032
// 0x0010 (0x0010 - 0x0000)
struct BP_FriendsList_C_OnFailure_5E28D2E54F38B10486BDCDAC1A2F5032 final
{
public:
	TArray<struct FMordhauFriend>                 Friends;                                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_BP_FriendsList_C_OnFailure_5E28D2E54F38B10486BDCDAC1A2F5032;

// Function BP_FriendsList.BP_FriendsList_C.IsFriend
// 0x00E8 (0x00E8 - 0x0000)
struct BP_FriendsList_C_IsFriend final
{
public:
	struct FPlayFabPlayer                         Player_0;                                          // 0x0000(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
	bool                                          IsFriend_0;                                        // 0x0060(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          bIsFriend;                                         // 0x0061(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0062(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_63[0x1];                                       // 0x0063(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_69[0x3];                                       // 0x0069(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FMordhauFriend                         CallFunc_Array_Get_Item;                           // 0x0078(0x0068)()
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x00E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Equal_PlayFabPlayer_ReturnValue;          // 0x00E2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_FriendsList_C_IsFriend;

// Function BP_FriendsList.BP_FriendsList_C.IsBlocked
// 0x0068 (0x0068 - 0x0000)
struct BP_FriendsList_C_IsBlocked final
{
public:
	struct FPlayFabPlayer                         Player_0;                                          // 0x0000(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
	bool                                          IsBlocked_0;                                       // 0x0060(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Array_Contains_ReturnValue;               // 0x0061(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_FriendsList_C_IsBlocked;

// Function BP_FriendsList.BP_FriendsList_C.Set Selected Tab
// 0x0028 (0x0028 - 0x0000)
struct BP_FriendsList_C_Set_Selected_Tab final
{
public:
	class UBP_ReusableNavTabButton_C*             Selected_Button;                                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_ReusableNavTabButton_C*             CallFunc_Array_Get_Item;                           // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_FriendsList_C_Set_Selected_Tab;

// Function BP_FriendsList.BP_FriendsList_C.ShowSearchFriends
// 0x0010 (0x0010 - 0x0000)
struct BP_FriendsList_C_ShowSearchFriends final
{
public:
	bool                                          bReset;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_FriendsList_C_ShowSearchFriends;

// Function BP_FriendsList.BP_FriendsList_C.SearchFriendsByUsername
// 0x0038 (0x0038 - 0x0000)
struct BP_FriendsList_C_SearchFriendsByUsername final
{
public:
	class FString                                 Username;                                          // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EPlatform                                     Temp_byte_Variable;                                // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPlatform                                     CallFunc_GetPlatform_ReturnValue;                  // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_13[0x5];                                       // 0x0013(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UMordhauGameUserSettings*               CallFunc_GetMordhauGameUserSettings_ReturnValue;   // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(bool bWasSuccessful, const struct FPlayFabApiError& Error, const struct FUsernameSearchResult& SearchResults)> K2Node_CreateDelegate_OutputDelegate; // 0x0020(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_GetCrossplayEnabled_ReturnValue;          // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EPlatform                                     K2Node_Select_Default;                             // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_FriendsList_C_SearchFriendsByUsername;

// Function BP_FriendsList.BP_FriendsList_C.OnSearchFriendsResult
// 0x00B0 (0x00B0 - 0x0000)
struct BP_FriendsList_C_OnSearchFriendsResult final
{
public:
	bool                                          IsSuccessful;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPlayFabApiError                       Error;                                             // 0x0008(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FUsernameSearchResult                  SearchResult;                                      // 0x0040(0x0040)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0080(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x0090(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_2;              // 0x00A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_FriendsList_C_OnSearchFriendsResult;

// Function BP_FriendsList.BP_FriendsList_C.OnShown
// 0x0001 (0x0001 - 0x0000)
struct BP_FriendsList_C_OnShown final
{
public:
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_FriendsList_C_OnShown;

// Function BP_FriendsList.BP_FriendsList_C.AnimateCloseSearchFriends
// 0x0018 (0x0018 - 0x0000)
struct BP_FriendsList_C_AnimateCloseSearchFriends final
{
public:
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0000(0x0010)(ZeroConstructor, NoDestructor)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_FriendsList_C_AnimateCloseSearchFriends;

// Function BP_FriendsList.BP_FriendsList_C.IsSearchVisible
// 0x0002 (0x0002 - 0x0000)
struct BP_FriendsList_C_IsSearchVisible final
{
public:
	bool                                          bIsVisible;                                        // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_FriendsList_C_IsSearchVisible;

// Function BP_FriendsList.BP_FriendsList_C.UpdateAllFriendsLists
// 0x0010 (0x0010 - 0x0000)
struct BP_FriendsList_C_UpdateAllFriendsLists final
{
public:
	bool                                          bClearLists;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimer_ReturnValue;                  // 0x0008(0x0008)(NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_FriendsList_C_UpdateAllFriendsLists;

// Function BP_FriendsList.BP_FriendsList_C.ClearFriendsList
// 0x0048 (0x0048 - 0x0000)
struct BP_FriendsList_C_ClearFriendsList final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue;               // 0x0010(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item;                           // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_FriendsListView_C*                  K2Node_DynamicCast_AsBP_Friends_List_View;         // 0x0038(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_FriendsList_C_ClearFriendsList;

// Function BP_FriendsList.BP_FriendsList_C.HandleKey
// 0x0050 (0x0050 - 0x0000)
struct BP_FriendsList_C_HandleKey final
{
public:
	struct FKey                                   InputKey;                                          // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
	class FText                                   CallFunc_Key_GetDisplayName_ReturnValue;           // 0x0018(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UBP_FriendsListView_C*                  CallFunc_GetTargetList_Listview;                   // 0x0040(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchString_CmpSuccess;                    // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_FriendsList_C_HandleKey;

// Function BP_FriendsList.BP_FriendsList_C.GetTargetList
// 0x0020 (0x0020 - 0x0000)
struct BP_FriendsList_C_GetTargetList final
{
public:
	class UBP_FriendsListView_C*                  ListView;                                          // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_FriendsListEntryType                        CallFunc_GetHoveredList_HoveredList;               // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A[0x6];                                        // 0x000A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_FriendsListView_C*                  CallFunc_Map_Find_Value;                           // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue_1;          // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x001A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x001B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_FriendsList_C_GetTargetList;

// Function BP_FriendsList.BP_FriendsList_C.GetHoveredList
// 0x0048 (0x0048 - 0x0000)
struct BP_FriendsList_C_GetHoveredList final
{
public:
	E_FriendsListEntryType                        HoveredList;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue;               // 0x0010(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item;                           // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_FriendsListView_C*                  K2Node_DynamicCast_AsBP_Friends_List_View;         // 0x0038(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsHovered_ReturnValue;                    // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_FriendsList_C_GetHoveredList;

// Function BP_FriendsList.BP_FriendsList_C.DeselectListEntries
// 0x0048 (0x0048 - 0x0000)
struct BP_FriendsList_C_DeselectListEntries final
{
public:
	E_FriendsListEntryType                        ExcludeList;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue;               // 0x0010(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item;                           // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_FriendsListView_C*                  K2Node_DynamicCast_AsBP_Friends_List_View;         // 0x0038(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_FriendsList_C_DeselectListEntries;

// Function BP_FriendsList.BP_FriendsList_C.MapListViews
// 0x0058 (0x0058 - 0x0000)
struct BP_FriendsList_C_MapListViews final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(E_FriendsListEntryType HoveringListType)> K2Node_CreateDelegate_OutputDelegate;   // 0x000C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue;               // 0x0020(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item;                           // 0x0038(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_FriendsListView_C*                  K2Node_DynamicCast_AsBP_Friends_List_View;         // 0x0048(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_FriendsList_C_MapListViews;

// Function BP_FriendsList.BP_FriendsList_C.SelectNearestFriendEntry
// 0x00C0 (0x00C0 - 0x0000)
struct BP_FriendsList_C_SelectNearestFriendEntry final
{
public:
	bool                                          Forward;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	E_FriendsListEntryType                        OriginList;                                        // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_FriendsListView_C*                  CallFunc_Map_Find_Value;                           // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UUserWidget*>                    CallFunc_GetDisplayedEntryWidgets_ReturnValue;     // 0x0020(0x0010)(ConstParm, ReferenceParm, ContainsInstancedReference)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x003D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3E[0x2];                                       // 0x003E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            CallFunc_Array_Get_Item;                           // 0x0048(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_FriendsListViewEntry_C*             K2Node_DynamicCast_AsBP_Friends_List_View_Entry;   // 0x0050(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_59[0x3];                                       // 0x0059(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometry                              CallFunc_GetCachedGeometry_ReturnValue;            // 0x005C(0x0038)(ConstParm, IsPlainOldData, NoDestructor)
	uint8                                         Pad_94[0x4];                                       // 0x0094(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IUserListEntry>        CallFunc_IsListItemSelected_UserListEntry_CastInput; // 0x0098(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper)
	bool                                          CallFunc_IsListItemSelected_ReturnValue;           // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A9[0x3];                                       // 0x00A9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              CallFunc_LocalToAbsolute_ReturnValue;              // 0x00AC(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_X;                          // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y;                          // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x00BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x00BD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_FriendsList_C_SelectNearestFriendEntry;

// Function BP_FriendsList.BP_FriendsList_C.AddFriendByShortID
// 0x0128 (0x0128 - 0x0000)
struct BP_FriendsList_C_AddFriendByShortID final
{
public:
	bool                                          bWasSuccessful;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPlayFabError                          Error;                                             // 0x0008(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FGetPlayerByShortIdResult              ShortIdResults;                                    // 0x0040(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   EntityId_0;                                        // 0x0078(0x0018)(Parm, OutParm)
	struct FUserSearchResult                      CallFunc_Array_Get_Item;                           // 0x0090(0x0078)()
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0108(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x010C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_10D[0x3];                                      // 0x010D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0110(0x0018)()
};
DUMPER7_ASSERTS_BP_FriendsList_C_AddFriendByShortID;

// Function BP_FriendsList.BP_FriendsList_C.RemoveMordhauBlockedFriends
// 0x00C0 (0x00C0 - 0x0000)
struct BP_FriendsList_C_RemoveMordhauBlockedFriends final
{
public:
	TArray<struct FMordhauFriend>                 Friends;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	TArray<struct FMordhauFriend>                 RealFriends;                                       // 0x0010(0x0010)(Parm, OutParm)
	TArray<struct FMordhauFriend>                 SanitazedFriends;                                  // 0x0020(0x0010)(Edit, BlueprintVisible)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMordhauFriend                         CallFunc_Array_Get_Item;                           // 0x0040(0x0068)()
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x00AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_AD[0x3];                                       // 0x00AD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_1;            // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Max_ReturnValue;                          // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_Contains_ReturnValue;               // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_FriendsList_C_RemoveMordhauBlockedFriends;

// Function BP_FriendsList.BP_FriendsList_C.Remove Playfab Blocked Friend
// 0x00B0 (0x00B0 - 0x0000)
struct BP_FriendsList_C_Remove_Playfab_Blocked_Friend final
{
public:
	TArray<struct FPlayFabPlayer>                 Friends;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	TArray<struct FPlayFabPlayer>                 RealFriends;                                       // 0x0010(0x0010)(Parm, OutParm)
	TArray<struct FPlayFabPlayer>                 SanitazedFriends;                                  // 0x0020(0x0010)(Edit, BlueprintVisible)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3D[0x3];                                       // 0x003D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPlayFabPlayer                         CallFunc_Array_Get_Item;                           // 0x0040(0x0060)(HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_Contains_ReturnValue;               // 0x00A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A5[0x3];                                       // 0x00A5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_1;            // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Max_ReturnValue;                          // 0x00AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_FriendsList_C_Remove_Playfab_Blocked_Friend;

// Function BP_FriendsList.BP_FriendsList_C.UpdateAddFriendDetailInfoWidget
// 0x0098 (0x0098 - 0x0000)
struct BP_FriendsList_C_UpdateAddFriendDetailInfoWidget final
{
public:
	struct FUserSearchResult                      SearchResult;                                      // 0x0000(0x0078)(BlueprintVisible, BlueprintReadOnly, Parm)
	class UBP_FriendSearchDetailInfo_C*           BP_FriendDetailInfo;                               // 0x0078(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_FriendSearchDetailInfo_C*           CallFunc_Create_ReturnValue;                       // 0x0088(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_FriendsList_C_UpdateAddFriendDetailInfoWidget;

// Function BP_FriendsList.BP_FriendsList_C.Update Invite Friend Detail Info Widget
// 0x0080 (0x0080 - 0x0000)
struct BP_FriendsList_C_Update_Invite_Friend_Detail_Info_Widget final
{
public:
	struct FPlayFabPlayer                         PlayFabPlayer;                                     // 0x0000(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
	class UBP_FriendSearchDetailInfo_C*           BP_FriendDetailInfo;                               // 0x0060(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_FriendSearchDetailInfo_C*           CallFunc_Create_ReturnValue;                       // 0x0070(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_FriendsList_C_Update_Invite_Friend_Detail_Info_Widget;

// Function BP_FriendsList.BP_FriendsList_C.UpdateBlockFriendDetailInfoWidget
// 0x0080 (0x0080 - 0x0000)
struct BP_FriendsList_C_UpdateBlockFriendDetailInfoWidget final
{
public:
	struct FPlayFabPlayer                         PlayFabPlayer;                                     // 0x0000(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
	class UBP_FriendSearchDetailInfo_C*           BP_FriendDetailInfo;                               // 0x0060(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_FriendSearchDetailInfo_C*           CallFunc_Create_ReturnValue;                       // 0x0070(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_FriendsList_C_UpdateBlockFriendDetailInfoWidget;

// Function BP_FriendsList.BP_FriendsList_C.UpdateUnblockFriendDetailInfoWidget
// 0x0080 (0x0080 - 0x0000)
struct BP_FriendsList_C_UpdateUnblockFriendDetailInfoWidget final
{
public:
	struct FPlayFabPlayer                         PlayFabPlayer;                                     // 0x0000(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
	class UBP_FriendSearchDetailInfo_C*           BP_FriendDetailInfo;                               // 0x0060(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_FriendSearchDetailInfo_C*           CallFunc_Create_ReturnValue;                       // 0x0070(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_FriendsList_C_UpdateUnblockFriendDetailInfoWidget;

}

