#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: modio

#include "Basic.hpp"

#include "modio_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class modio.CallbackProxy_AddMetadataKVP
// 0x0080 (0x00B0 - 0x0030)
class UCallbackProxy_AddMetadataKVP final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x58];                                      // 0x0030(0x0058)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onSuccess;                 // 0x0090(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onFailure;                 // 0x00A0(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_AddMetadataKVP* AddMetadataKVP(class UObject* WorldContext, int32 ModId, const TMap<class FString, class FString>& MetadataKVP);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_AddMetadataKVP")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_AddMetadataKVP")
	}
	static class UCallbackProxy_AddMetadataKVP* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_AddMetadataKVP>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_AddMetadataKVP;

// Class modio.CallbackProxy_AddMod
// 0x00B0 (0x00E0 - 0x0030)
class UCallbackProxy_AddMod final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x88];                                      // 0x0030(0x0088)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const struct FModioMod& Mod)> onSuccess; // 0x00C0(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const struct FModioMod& Mod)> onFailure; // 0x00D0(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_AddMod* AddMod(class UObject* WorldContext, const struct FModioModCreator& ModCreator);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_AddMod")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_AddMod")
	}
	static class UCallbackProxy_AddMod* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_AddMod>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_AddMod;

// Class modio.CallbackProxy_AddModDependencies
// 0x0040 (0x0070 - 0x0030)
class UCallbackProxy_AddModDependencies final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x18];                                      // 0x0030(0x0018)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onSuccess;                 // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onFailure;                 // 0x0060(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_AddModDependencies* AddModDependencies(class UObject* WorldContext, int32 ModId, const TArray<int32>& Dependencies);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_AddModDependencies")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_AddModDependencies")
	}
	static class UCallbackProxy_AddModDependencies* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_AddModDependencies>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_AddModDependencies;

// Class modio.CallbackProxy_AddModImages
// 0x0040 (0x0070 - 0x0030)
class UCallbackProxy_AddModImages final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x18];                                      // 0x0030(0x0018)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onSuccess;                 // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onFailure;                 // 0x0060(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_AddModImages* AddModImages(class UObject* WorldContext, int32 ModId, const TArray<class FString>& ImagePaths);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_AddModImages")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_AddModImages")
	}
	static class UCallbackProxy_AddModImages* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_AddModImages>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_AddModImages;

// Class modio.CallbackProxy_AddModLogo
// 0x0040 (0x0070 - 0x0030)
class UCallbackProxy_AddModLogo final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x18];                                      // 0x0030(0x0018)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onSuccess;                 // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onFailure;                 // 0x0060(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_AddModLogo* AddModLogo(class UObject* WorldContext, int32 ModId, const class FString& LogoPath);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_AddModLogo")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_AddModLogo")
	}
	static class UCallbackProxy_AddModLogo* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_AddModLogo>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_AddModLogo;

// Class modio.CallbackProxy_AddModRating
// 0x0030 (0x0060 - 0x0030)
class UCallbackProxy_AddModRating final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x8];                                       // 0x0030(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onSuccess;                 // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onFailure;                 // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_AddModRating* AddModRating(class UObject* WorldContext, int32 ModId, bool IsRatingPositive);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_AddModRating")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_AddModRating")
	}
	static class UCallbackProxy_AddModRating* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_AddModRating>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_AddModRating;

// Class modio.CallbackProxy_AddModSketchfabLinks
// 0x0040 (0x0070 - 0x0030)
class UCallbackProxy_AddModSketchfabLinks final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x18];                                      // 0x0030(0x0018)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onSuccess;                 // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onFailure;                 // 0x0060(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_AddModSketchfabLinks* AddModSketchfabLinks(class UObject* WorldContext, int32 ModId, const TArray<class FString>& SketchfabLinks);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_AddModSketchfabLinks")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_AddModSketchfabLinks")
	}
	static class UCallbackProxy_AddModSketchfabLinks* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_AddModSketchfabLinks>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_AddModSketchfabLinks;

// Class modio.CallbackProxy_AddModTags
// 0x0040 (0x0070 - 0x0030)
class UCallbackProxy_AddModTags final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x18];                                      // 0x0030(0x0018)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onSuccess;                 // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onFailure;                 // 0x0060(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_AddModTags* AddModTags(class UObject* WorldContext, int32 ModId, const TArray<class FString>& Tags);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_AddModTags")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_AddModTags")
	}
	static class UCallbackProxy_AddModTags* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_AddModTags>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_AddModTags;

// Class modio.CallbackProxy_AddModYoutubeLinks
// 0x0040 (0x0070 - 0x0030)
class UCallbackProxy_AddModYoutubeLinks final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x18];                                      // 0x0030(0x0018)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onSuccess;                 // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onFailure;                 // 0x0060(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_AddModYoutubeLinks* AddModYoutubeLinks(class UObject* WorldContext, int32 ModId, const TArray<class FString>& YoutubeLinks);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_AddModYoutubeLinks")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_AddModYoutubeLinks")
	}
	static class UCallbackProxy_AddModYoutubeLinks* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_AddModYoutubeLinks>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_AddModYoutubeLinks;

// Class modio.CallbackProxy_DeleteMetadataKVP
// 0x0080 (0x00B0 - 0x0030)
class UCallbackProxy_DeleteMetadataKVP final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x58];                                      // 0x0030(0x0058)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onSuccess;                 // 0x0090(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onFailure;                 // 0x00A0(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_DeleteMetadataKVP* DeleteMetadataKVP(class UObject* WorldContext, int32 ModId, const TMap<class FString, class FString>& MetadataKVP);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_DeleteMetadataKVP")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_DeleteMetadataKVP")
	}
	static class UCallbackProxy_DeleteMetadataKVP* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_DeleteMetadataKVP>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_DeleteMetadataKVP;

// Class modio.CallbackProxy_DeleteModDependencies
// 0x0040 (0x0070 - 0x0030)
class UCallbackProxy_DeleteModDependencies final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x18];                                      // 0x0030(0x0018)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onSuccess;                 // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onFailure;                 // 0x0060(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_DeleteModDependencies* DeleteModDependencies(class UObject* WorldContext, int32 ModId, const TArray<int32>& Dependencies);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_DeleteModDependencies")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_DeleteModDependencies")
	}
	static class UCallbackProxy_DeleteModDependencies* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_DeleteModDependencies>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_DeleteModDependencies;

// Class modio.CallbackProxy_DeleteModImages
// 0x0040 (0x0070 - 0x0030)
class UCallbackProxy_DeleteModImages final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x18];                                      // 0x0030(0x0018)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onSuccess;                 // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onFailure;                 // 0x0060(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_DeleteModImages* DeleteModImages(class UObject* WorldContext, int32 ModId, const TArray<class FString>& ImagePaths);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_DeleteModImages")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_DeleteModImages")
	}
	static class UCallbackProxy_DeleteModImages* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_DeleteModImages>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_DeleteModImages;

// Class modio.CallbackProxy_DeleteModSketchfabLinks
// 0x0040 (0x0070 - 0x0030)
class UCallbackProxy_DeleteModSketchfabLinks final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x18];                                      // 0x0030(0x0018)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onSuccess;                 // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onFailure;                 // 0x0060(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_DeleteModSketchfabLinks* DeleteModSketchfabLinks(class UObject* WorldContext, int32 ModId, const TArray<class FString>& SketchfabLinks);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_DeleteModSketchfabLinks")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_DeleteModSketchfabLinks")
	}
	static class UCallbackProxy_DeleteModSketchfabLinks* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_DeleteModSketchfabLinks>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_DeleteModSketchfabLinks;

// Class modio.CallbackProxy_DeleteModTags
// 0x0040 (0x0070 - 0x0030)
class UCallbackProxy_DeleteModTags final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x18];                                      // 0x0030(0x0018)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onSuccess;                 // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onFailure;                 // 0x0060(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_DeleteModTags* DeleteModTags(class UObject* WorldContext, int32 ModId, const TArray<class FString>& Tags);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_DeleteModTags")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_DeleteModTags")
	}
	static class UCallbackProxy_DeleteModTags* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_DeleteModTags>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_DeleteModTags;

// Class modio.CallbackProxy_DeleteModYoutubeLinks
// 0x0040 (0x0070 - 0x0030)
class UCallbackProxy_DeleteModYoutubeLinks final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x18];                                      // 0x0030(0x0018)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onSuccess;                 // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onFailure;                 // 0x0060(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_DeleteModYoutubeLinks* DeleteModYoutubeLinks(class UObject* WorldContext, int32 ModId, const TArray<class FString>& YoutubeLinks);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_DeleteModYoutubeLinks")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_DeleteModYoutubeLinks")
	}
	static class UCallbackProxy_DeleteModYoutubeLinks* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_DeleteModYoutubeLinks>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_DeleteModYoutubeLinks;

// Class modio.CallbackProxy_DownloadModfilesById
// 0x0038 (0x0068 - 0x0030)
class UCallbackProxy_DownloadModfilesById final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x10];                                      // 0x0030(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, bool mods_are_updated)> onSuccess; // 0x0048(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, bool mods_are_updated)> onFailure; // 0x0058(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_DownloadModfilesById* DownloadModfilesById(class UObject* WorldContext, const TArray<int32>& ModIds);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_DownloadModfilesById")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_DownloadModfilesById")
	}
	static class UCallbackProxy_DownloadModfilesById* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_DownloadModfilesById>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_DownloadModfilesById;

// Class modio.CallbackProxy_DownloadSubscribedModfiles
// 0x0030 (0x0060 - 0x0030)
class UCallbackProxy_DownloadSubscribedModfiles final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x8];                                       // 0x0030(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, bool mods_are_updated)> onSuccess; // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, bool mods_are_updated)> onFailure; // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_DownloadSubscribedModfiles* DownloadSubscribedModfiles(class UObject* WorldContext, bool UninstallUnsubscribed);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_DownloadSubscribedModfiles")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_DownloadSubscribedModfiles")
	}
	static class UCallbackProxy_DownloadSubscribedModfiles* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_DownloadSubscribedModfiles>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_DownloadSubscribedModfiles;

// Class modio.CallbackProxy_EditMod
// 0x0098 (0x00C8 - 0x0030)
class UCallbackProxy_EditMod final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x70];                                      // 0x0030(0x0070)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const struct FModioMod& Mod)> onSuccess; // 0x00A8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const struct FModioMod& Mod)> onFailure; // 0x00B8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_EditMod* EditMod(class UObject* WorldContext, int32 ModId, const struct FModioModEditor& ModEditor);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_EditMod")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_EditMod")
	}
	static class UCallbackProxy_EditMod* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_EditMod>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_EditMod;

// Class modio.CallbackProxy_EmailExchange
// 0x0038 (0x0068 - 0x0030)
class UCallbackProxy_EmailExchange final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x10];                                      // 0x0030(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onSuccess;                 // 0x0048(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onFailure;                 // 0x0058(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_EmailExchange* EmailExchange(class UObject* WorldContext, const class FString& SecurityCode);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_EmailExchange")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_EmailExchange")
	}
	static class UCallbackProxy_EmailExchange* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_EmailExchange>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_EmailExchange;

// Class modio.CallbackProxy_EmailRequest
// 0x0038 (0x0068 - 0x0030)
class UCallbackProxy_EmailRequest final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x10];                                      // 0x0030(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onSuccess;                 // 0x0048(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onFailure;                 // 0x0058(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_EmailRequest* EmailRequest(class UObject* WorldContext, const class FString& Email);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_EmailRequest")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_EmailRequest")
	}
	static class UCallbackProxy_EmailRequest* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_EmailRequest>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_EmailRequest;

// Class modio.CallbackProxy_GalaxyAuth
// 0x0038 (0x0068 - 0x0030)
class UCallbackProxy_GalaxyAuth final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x10];                                      // 0x0030(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onSuccess;                 // 0x0048(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onFailure;                 // 0x0058(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_GalaxyAuth* GalaxyAuth(class UObject* WorldContext, const class FString& Appdata);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_GalaxyAuth")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_GalaxyAuth")
	}
	static class UCallbackProxy_GalaxyAuth* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_GalaxyAuth>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_GalaxyAuth;

// Class modio.CallbackProxy_GetAllMetadataKVP
// 0x0030 (0x0060 - 0x0030)
class UCallbackProxy_GetAllMetadataKVP final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x8];                                       // 0x0030(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const TArray<struct FModioMetadataKVP>& MetadataKVP)> onSuccess; // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const TArray<struct FModioMetadataKVP>& MetadataKVP)> onFailure; // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_GetAllMetadataKVP* GetAllMetadataKVP(class UObject* WorldContext, int32 ModId);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_GetAllMetadataKVP")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_GetAllMetadataKVP")
	}
	static class UCallbackProxy_GetAllMetadataKVP* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_GetAllMetadataKVP>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_GetAllMetadataKVP;

// Class modio.CallbackProxy_GetAllModDependencies
// 0x0030 (0x0060 - 0x0030)
class UCallbackProxy_GetAllModDependencies final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x8];                                       // 0x0030(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const TArray<struct FModioModDependency>& ModDependencies)> onSuccess; // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const TArray<struct FModioModDependency>& ModDependencies)> onFailure; // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_GetAllModDependencies* GetAllModDependencies(class UObject* WorldContext, int32 ModId);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_GetAllModDependencies")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_GetAllModDependencies")
	}
	static class UCallbackProxy_GetAllModDependencies* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_GetAllModDependencies>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_GetAllModDependencies;

// Class modio.CallbackProxy_GetAllModfiles
// 0x0030 (0x0060 - 0x0030)
class UCallbackProxy_GetAllModfiles final : public UOnlineBlueprintCallProxyBase
{
public:
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const TArray<struct FModioModfile>& ModFile)> onSuccess; // 0x0030(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const TArray<struct FModioModfile>& ModFile)> onFailure; // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	class UObject*                                WorldContextObject;                                // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_58[0x8];                                       // 0x0058(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UCallbackProxy_GetAllModfiles* GetAllModfiles(class UObject* WorldContext, int32 ModId);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_GetAllModfiles")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_GetAllModfiles")
	}
	static class UCallbackProxy_GetAllModfiles* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_GetAllModfiles>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_GetAllModfiles;

// Class modio.CallbackProxy_GetAllMods
// 0x0068 (0x0098 - 0x0030)
class UCallbackProxy_GetAllMods final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x40];                                      // 0x0030(0x0040)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const TArray<struct FModioMod>& Mods)> onSuccess; // 0x0078(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const TArray<struct FModioMod>& Mods)> onFailure; // 0x0088(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_GetAllMods* GetAllMods(class UObject* WorldContext, const struct FModioFilterCreator& Filter, const TArray<class FString>& ModTags, int32 Limit, int32 Offset);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_GetAllMods")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_GetAllMods")
	}
	static class UCallbackProxy_GetAllMods* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_GetAllMods>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_GetAllMods;

// Class modio.CallbackProxy_GetAllModTags
// 0x0030 (0x0060 - 0x0030)
class UCallbackProxy_GetAllModTags final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x8];                                       // 0x0030(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const TArray<struct FModioModTag>& ModTags)> onSuccess; // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const TArray<struct FModioModTag>& ModTags)> onFailure; // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_GetAllModTags* GetAllModTags(class UObject* WorldContext, int32 ModId);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_GetAllModTags")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_GetAllModTags")
	}
	static class UCallbackProxy_GetAllModTags* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_GetAllModTags>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_GetAllModTags;

// Class modio.CallbackProxy_GetAuthenticatedUser
// 0x0028 (0x0058 - 0x0030)
class UCallbackProxy_GetAuthenticatedUser final : public UOnlineBlueprintCallProxyBase
{
public:
	class UObject*                                WorldContextObject;                                // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const struct FModioUser& User)> onSuccess; // 0x0038(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const struct FModioUser& User)> onFailure; // 0x0048(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_GetAuthenticatedUser* GetAuthenticatedUser(class UObject* WorldContext);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_GetAuthenticatedUser")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_GetAuthenticatedUser")
	}
	static class UCallbackProxy_GetAuthenticatedUser* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_GetAuthenticatedUser>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_GetAuthenticatedUser;

// Class modio.CallbackProxy_GetGame
// 0x0030 (0x0060 - 0x0030)
class UCallbackProxy_GetGame final : public UOnlineBlueprintCallProxyBase
{
public:
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const struct FModioGame& Game)> onSuccess; // 0x0030(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const struct FModioGame& Game)> onFailure; // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_50[0x8];                                       // 0x0050(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UCallbackProxy_GetGame* GetGame(class UObject* WorldContext, int32 GameId);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_GetGame")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_GetGame")
	}
	static class UCallbackProxy_GetGame* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_GetGame>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_GetGame;

// Class modio.CallbackProxy_GetMod
// 0x0030 (0x0060 - 0x0030)
class UCallbackProxy_GetMod final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x8];                                       // 0x0030(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const struct FModioMod& Mod)> onSuccess; // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const struct FModioMod& Mod)> onFailure; // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_GetMod* GetMod(class UObject* WorldContext, int32 ModId);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_GetMod")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_GetMod")
	}
	static class UCallbackProxy_GetMod* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_GetMod>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_GetMod;

// Class modio.CallbackProxy_GetUserEvents
// 0x0030 (0x0060 - 0x0030)
class UCallbackProxy_GetUserEvents final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x8];                                       // 0x0030(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const TArray<struct FModioUserEvent>& UserEvents)> onSuccess; // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const TArray<struct FModioUserEvent>& UserEvents)> onFailure; // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_GetUserEvents* GetUserEvents(class UObject* WorldContext, int32 Limit, int32 Offset);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_GetUserEvents")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_GetUserEvents")
	}
	static class UCallbackProxy_GetUserEvents* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_GetUserEvents>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_GetUserEvents;

// Class modio.CallbackProxy_GetUserModfiles
// 0x0030 (0x0060 - 0x0030)
class UCallbackProxy_GetUserModfiles final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x8];                                       // 0x0030(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const TArray<struct FModioModfile>& Modfiles)> onSuccess; // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const TArray<struct FModioModfile>& Modfiles)> onFailure; // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_GetUserModfiles* GetUserModfiles(class UObject* WorldContext, int32 Limit, int32 Offset);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_GetUserModfiles")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_GetUserModfiles")
	}
	static class UCallbackProxy_GetUserModfiles* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_GetUserModfiles>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_GetUserModfiles;

// Class modio.CallbackProxy_GetUserMods
// 0x0068 (0x0098 - 0x0030)
class UCallbackProxy_GetUserMods final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x40];                                      // 0x0030(0x0040)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const TArray<struct FModioMod>& Mods)> onSuccess; // 0x0078(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const TArray<struct FModioMod>& Mods)> onFailure; // 0x0088(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_GetUserMods* GetUserMods(class UObject* WorldContext, const struct FModioFilterCreator& FilterCreator, const TArray<class FString>& ModTags, int32 Limit, int32 Offset);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_GetUserMods")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_GetUserMods")
	}
	static class UCallbackProxy_GetUserMods* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_GetUserMods>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_GetUserMods;

// Class modio.CallbackProxy_GetUserRatings
// 0x0030 (0x0060 - 0x0030)
class UCallbackProxy_GetUserRatings final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x8];                                       // 0x0030(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const TArray<struct FModioRating>& Ratings)> onSuccess; // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const TArray<struct FModioRating>& Ratings)> onFailure; // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_GetUserRatings* GetUserRatings(class UObject* WorldContext, int32 Limit, int32 Offset);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_GetUserRatings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_GetUserRatings")
	}
	static class UCallbackProxy_GetUserRatings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_GetUserRatings>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_GetUserRatings;

// Class modio.CallbackProxy_GetUserSubscriptions
// 0x0068 (0x0098 - 0x0030)
class UCallbackProxy_GetUserSubscriptions final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x40];                                      // 0x0030(0x0040)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const TArray<struct FModioMod>& Mods)> onSuccess; // 0x0078(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const TArray<struct FModioMod>& Mods)> onFailure; // 0x0088(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_GetUserSubscriptions* GetUserSubscriptions(class UObject* WorldContext, const struct FModioFilterCreator& FilterCreator, const TArray<class FString>& ModTags, int32 Limit, int32 Offset);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_GetUserSubscriptions")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_GetUserSubscriptions")
	}
	static class UCallbackProxy_GetUserSubscriptions* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_GetUserSubscriptions>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_GetUserSubscriptions;

// Class modio.CallbackProxy_OculusAuth
// 0x0080 (0x00B0 - 0x0030)
class UCallbackProxy_OculusAuth final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x58];                                      // 0x0030(0x0058)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onSuccess;                 // 0x0090(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onFailure;                 // 0x00A0(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_OculusAuth* OculusAuth(class UObject* WorldContext, const class FString& Nonce, const class FString& OculusUserId, const class FString& AccessToken, const class FString& Email, const class FString& Device, int32 DateExpires);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_OculusAuth")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_OculusAuth")
	}
	static class UCallbackProxy_OculusAuth* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_OculusAuth>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_OculusAuth;

// Class modio.CallbackProxy_SetModDownloadListener
// 0x0028 (0x0058 - 0x0030)
class UCallbackProxy_SetModDownloadListener final : public UOnlineBlueprintCallProxyBase
{
public:
	class UObject*                                WorldContextObject;                                // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(int32 ResponseCode, int32 ModId)> onSuccess;                       // 0x0038(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(int32 ResponseCode, int32 ModId)> onFailure;                       // 0x0048(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_SetModDownloadListener* SetModDownloadListener(class UObject* WorldContext);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_SetModDownloadListener")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_SetModDownloadListener")
	}
	static class UCallbackProxy_SetModDownloadListener* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_SetModDownloadListener>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_SetModDownloadListener;

// Class modio.CallbackProxy_SetModEventListener
// 0x0028 (0x0058 - 0x0030)
class UCallbackProxy_SetModEventListener final : public UOnlineBlueprintCallProxyBase
{
public:
	class UObject*                                WorldContextObject;                                // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const TArray<struct FModioModEvent>& ModEvents)> onSuccess; // 0x0038(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const TArray<struct FModioModEvent>& ModEvents)> onFailure; // 0x0048(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_SetModEventListener* SetModEventListener(class UObject* WorldContext);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_SetModEventListener")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_SetModEventListener")
	}
	static class UCallbackProxy_SetModEventListener* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_SetModEventListener>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_SetModEventListener;

// Class modio.CallbackProxy_SetModfileUploadListener
// 0x0028 (0x0058 - 0x0030)
class UCallbackProxy_SetModfileUploadListener final : public UOnlineBlueprintCallProxyBase
{
public:
	class UObject*                                WorldContextObject;                                // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(int32 ResponseCode, int32 ModId)> onSuccess;                       // 0x0038(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(int32 ResponseCode, int32 ModId)> onFailure;                       // 0x0048(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_SetModfileUploadListener* SetModfileUploadListener(class UObject* WorldContext);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_SetModfileUploadListener")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_SetModfileUploadListener")
	}
	static class UCallbackProxy_SetModfileUploadListener* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_SetModfileUploadListener>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_SetModfileUploadListener;

// Class modio.CallbackProxy_SteamAuth
// 0x0038 (0x0068 - 0x0030)
class UCallbackProxy_SteamAuth final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x10];                                      // 0x0030(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onSuccess;                 // 0x0048(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onFailure;                 // 0x0058(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_SteamAuth* SteamAuth(class UObject* WorldContext, const class FString& Base64Ticket);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_SteamAuth")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_SteamAuth")
	}
	static class UCallbackProxy_SteamAuth* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_SteamAuth>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_SteamAuth;

// Class modio.CallbackProxy_SubmitReport
// 0x0058 (0x0088 - 0x0030)
class UCallbackProxy_SubmitReport final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x30];                                      // 0x0030(0x0030)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onSuccess;                 // 0x0068(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onFailure;                 // 0x0078(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_SubmitReport* SubmitReport(class UObject* WorldContext, EModioResourceType Resource, int32 ID, EModioReportType Report, const class FString& Name_0, const class FString& Summary);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_SubmitReport")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_SubmitReport")
	}
	static class UCallbackProxy_SubmitReport* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_SubmitReport>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_SubmitReport;

// Class modio.CallbackProxy_SubscribeToMod
// 0x0030 (0x0060 - 0x0030)
class UCallbackProxy_SubscribeToMod final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x8];                                       // 0x0030(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const struct FModioMod& Mod)> onSuccess; // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response, const struct FModioMod& Mod)> onFailure; // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_SubscribeToMod* SubscribeToMod(class UObject* WorldContext, int32 ModId);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_SubscribeToMod")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_SubscribeToMod")
	}
	static class UCallbackProxy_SubscribeToMod* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_SubscribeToMod>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_SubscribeToMod;

// Class modio.CallbackProxy_UninstallUnavailableMods
// 0x0028 (0x0058 - 0x0030)
class UCallbackProxy_UninstallUnavailableMods final : public UOnlineBlueprintCallProxyBase
{
public:
	class UObject*                                WorldContextObject;                                // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onSuccess;                 // 0x0038(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onFailure;                 // 0x0048(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_UninstallUnavailableMods* UninstallUnavailableMods(class UObject* WorldContext);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_UninstallUnavailableMods")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_UninstallUnavailableMods")
	}
	static class UCallbackProxy_UninstallUnavailableMods* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_UninstallUnavailableMods>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_UninstallUnavailableMods;

// Class modio.CallbackProxy_UnsubscribeFromMod
// 0x0030 (0x0060 - 0x0030)
class UCallbackProxy_UnsubscribeFromMod final : public UOnlineBlueprintCallProxyBase
{
public:
	uint8                                         Pad_30[0x8];                                       // 0x0030(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                WorldContextObject;                                // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onSuccess;                 // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FModioResponse& response)> onFailure;                 // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UCallbackProxy_UnsubscribeFromMod* UnsubscribeFromMod(class UObject* WorldContext, int32 ModId);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CallbackProxy_UnsubscribeFromMod")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CallbackProxy_UnsubscribeFromMod")
	}
	static class UCallbackProxy_UnsubscribeFromMod* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCallbackProxy_UnsubscribeFromMod>();
	}
};
DUMPER7_ASSERTS_UCallbackProxy_UnsubscribeFromMod;

// Class modio.ModioActorComponent
// 0x0010 (0x00C0 - 0x00B0)
class UModioActorComponent final : public UActorComponent
{
public:
	uint8                                         Pad_B0[0x10];                                      // 0x00B0(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ModioActorComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ModioActorComponent")
	}
	static class UModioActorComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UModioActorComponent>();
	}
};
DUMPER7_ASSERTS_UModioActorComponent;

// Class modio.ModioFunctionLibrary
// 0x0000 (0x0028 - 0x0028)
class UModioFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	static void AuthenticateViaToken(class UObject* WorldContextObject, const class FString& AccessToken);
	static void ModioAddModfile(class UObject* WorldContextObject, int32 ModId, const struct FModioModfileCreator& ModfileCreator);
	static void ModioCancelModDownload(class UObject* WorldContextObject, int32 ModId);
	static void ModioCurrentUser(class UObject* WorldContextObject, struct FModioUser* User);
	static void ModioDownloadMod(class UObject* WorldContextObject, int32 ModId);
	static void ModioGetAllDownloadedMods(class UObject* WorldContextObject, TArray<int32>* DownloadedMods);
	static void ModioGetAllInstalledMods(class UObject* WorldContextObject, TArray<struct FModioInstalledMod>* InstalledMods);
	static void ModioGetCurrentUserModRating(class UObject* WorldContextObject, int32 ModId, uint8* ModRating);
	static void ModioGetCurrentUserSubscriptions(class UObject* WorldContextObject, TArray<int32>* ModIds);
	static void ModioGetInstalledMod(class UObject* WorldContextObject, int32 ModId, class FString* Path, struct FModioMod* Mod);
	static void ModioGetModDownloadQueue(class UObject* WorldContextObject, TArray<struct FModioQueuedModDownload>* QueuedMods);
	static void ModioGetModfileUploadQueue(class UObject* WorldContextObject, TArray<struct FModioQueuedModfileUpload>* UploadQueue);
	static void ModioGetModState(class UObject* WorldContextObject, int32 ModId, uint8* ModState);
	static void ModioInstallDownloadedMods(class UObject* WorldContextObject);
	static void ModioIsCurrentUserSubscribed(class UObject* WorldContextObject, int32 ModId, bool* IsSubscribed);
	static void ModioIsLoggedIn(class UObject* WorldContextObject, bool* IsLoggedIn);
	static void ModioLogout(class UObject* WorldContextObject);
	static void ModioPauseDownloads(class UObject* WorldContextObject);
	static void ModioPollEvents(class UObject* WorldContextObject);
	static void ModioPrioritizeModDownload(class UObject* WorldContextObject, int32 ModId);
	static void ModioProcess(class UObject* WorldContextObject);
	static void ModioResumeDownloads(class UObject* WorldContextObject);
	static void ModioSetModEventsPollInterval(class UObject* WorldContextObject, int32 IntervalInSeconds);
	static void ModioSetUserEventsPollInterval(class UObject* WorldContextObject, int32 IntervalInSeconds);
	static void ModioUninstallMod(class UObject* WorldContextObject, int32 ModId, bool* SuccessfullyUninstalled);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ModioFunctionLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ModioFunctionLibrary")
	}
	static class UModioFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UModioFunctionLibrary>();
	}
};
DUMPER7_ASSERTS_UModioFunctionLibrary;

// Class modio.ModioSettings
// 0x0030 (0x0058 - 0x0028)
class UModioSettings final : public UObject
{
public:
	int32                                         GameId;                                            // 0x0028(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 ApiKey;                                            // 0x0030(0x0010)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 RootDirectory;                                     // 0x0040(0x0010)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         bRootDirectoryIsInUserSettingsDirectory : 1;       // 0x0050(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, Config, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bRunOnDedicatedServer : 1;                         // 0x0050(0x0001)(BitIndex: 0x01, PropSize: 0x0001 (Edit, Config, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bIsLiveEnvironment : 1;                            // 0x0050(0x0001)(BitIndex: 0x02, PropSize: 0x0001 (Edit, Config, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bInstallOnModDownload : 1;                         // 0x0050(0x0001)(BitIndex: 0x03, PropSize: 0x0001 (Edit, Config, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bRetrieveModsFromOtherGames : 1;                   // 0x0050(0x0001)(BitIndex: 0x04, PropSize: 0x0001 (Edit, Config, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bEnablePolling : 1;                                // 0x0050(0x0001)(BitIndex: 0x05, PropSize: 0x0001 (Edit, Config, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ModioSettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ModioSettings")
	}
	static class UModioSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UModioSettings>();
	}
};
DUMPER7_ASSERTS_UModioSettings;

}

